# Generated by Django 2.1.1 on 2019-02-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='author',
            field=models.CharField(default='Sagar', max_length=200),
        ),
    ]
