# Generated by Django 2.1.1 on 2019-02-28 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_memory_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=250)),
                ('sent_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
